# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcu.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mcu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcu.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\nLedRequest\x12\n\n\x02on\x18\x01 \x01(\x08\"\x1f\n\rMatrixRequest\x12\x0e\n\x06pixels\x18\x01 \x03(\r2p\n\nMcuService\x12-\n\x06SetLed\x12\x0b.LedRequest\x1a\x16.google.protobuf.Empty\x12\x33\n\tSetMatrix\x12\x0e.MatrixRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEDREQUEST']._serialized_start=42
  _globals['_LEDREQUEST']._serialized_end=66
  _globals['_MATRIXREQUEST']._serialized_start=68
  _globals['_MATRIXREQUEST']._serialized_end=99
  _globals['_MCUSERVICE']._serialized_start=101
  _globals['_MCUSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
